apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.levizitting.com
  admin.enabled: "true"
  oidc.tls.insecure.skip.verify: "true"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $argocd-github-dex:client-id
          clientSecret: $argocd-github-dex:client-secret
          useLoginAsID: true
